apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: pong
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
