apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pingpong-dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: daoquocquyen/ping
    newTag: 0.0.3
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml